various file cleanup

diff --git a/bin/git-credential-bitwarden b/bin/git-credential-bitwarden
--- a/bin/git-credential-bitwarden
+++ b/bin/git-credential-bitwarden
@@ -16,54 +16,54 @@ declare -A host_map=(
 )
 
 if [ "x$1" == "x-l" ]; then
-	shift
-	bw_user=$1
-	shift
+  shift
+  bw_user=$1
+  shift
 fi
 
 if [ "x$1" == "xget" ]; then
-	read line
-	while [ -n "$line" ]; do
-		key=${line%%=*}
-		value=${line#*=}
-		params[$key]=$value
-		read line
-	done
+  read line
+  while [ -n "$line" ]; do
+    key=${line%%=*}
+    value=${line#*=}
+    params[$key]=$value
+    read line
+  done
 
   host=${params["host"]}
-	if [ "x${params['protocol']}" != "xhttps" ]; then
-		exit
-	fi
+  if [ "x${params['protocol']}" != "xhttps" ]; then
+    exit
+  fi
 
-	if [ -z "$host" ]; then
-		exit
-	fi
+  if [ -z "$host" ]; then
+    exit
+  fi
 
-	bw list items > /dev/null 2>&1
-	if [ $? -ne 0 ]; then
-		if [ -z "$bw_user" ]; then
-			read -p "Bitwarden username: " bw_user < /dev/tty > /dev/tty
-		fi
-		if [ -z "$bw_user" ]; then
-			exit
-		fi
-		bw login "$bw_user" > /dev/null
-		if [ $? -ne 0 ]; then
-			echo "Failed to login to bitwarden" > /dev/stderr
-			exit
-		fi
-	fi
+  bw list items > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    if [ -z "$bw_user" ]; then
+      read -p "Bitwarden username: " bw_user < /dev/tty > /dev/tty
+    fi
+    if [ -z "$bw_user" ]; then
+      exit
+    fi
+    bw login "$bw_user" > /dev/null
+    if [ $? -ne 0 ]; then
+      echo "Failed to login to bitwarden" > /dev/stderr
+      exit
+    fi
+  fi
 
   key=${host_map[$host]:-$host}
   user="$(bw get username $key)"
   pass="$(bw get password $key)"
 
-	if [ "x$user" == "x" ] || [ "x$pass" == "x" ]; then
-		echo "Couldn't find host in bitwarden DB." > /dev/stderr
-		exit
-	fi
+  if [ "x$user" == "x" ] || [ "x$pass" == "x" ]; then
+    echo "Couldn't find host in bitwarden DB." > /dev/stderr
+    exit
+  fi
 
-	echo username=$user
-	echo password=$pass
+  echo username=$user
+  echo password=$pass
 fi
 
diff --git a/bin/git-credential-lastpass b/bin/git-credential-lastpass
--- a/bin/git-credential-lastpass
+++ b/bin/git-credential-lastpass
@@ -15,54 +15,54 @@ declare -A host_map=(
 )
 
 if [ "x$1" == "x-l" ]; then
-	shift
-	lpassuser=$1
-	shift
+  shift
+  lpassuser=$1
+  shift
 fi
 
 if [ "x$1" == "xget" ]; then
-	read line
-	while [ -n "$line" ]; do
-		key=${line%%=*}
-		value=${line#*=}
-		params[$key]=$value
-		read line
-	done
+  read line
+  while [ -n "$line" ]; do
+    key=${line%%=*}
+    value=${line#*=}
+    params[$key]=$value
+    read line
+  done
 
   host=${params["host"]}
-	if [ "x${params['protocol']}" != "xhttps" ]; then
-		exit
-	fi
+  if [ "x${params['protocol']}" != "xhttps" ]; then
+    exit
+  fi
 
-	if [ -z "$host" ]; then
-		exit
-	fi
+  if [ -z "$host" ]; then
+    exit
+  fi
 
-	lpass ls > /dev/null 2>&1
-	if [ $? -ne 0 ]; then
-		if [ -z "$lpassuser" ]; then
-			read -p "Lastpass username: " lpassuser < /dev/tty > /dev/tty
-		fi
-		if [ -z "$lpassuser" ]; then
-			exit
-		fi
-		lpass login $lpassuser > /dev/null
-		if [ $? -ne 0 ]; then
-			echo "Failed to login to lastpass" > /dev/stderr
-			exit
-		fi
-	fi
+  lpass ls > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    if [ -z "$lpassuser" ]; then
+      read -p "Lastpass username: " lpassuser < /dev/tty > /dev/tty
+    fi
+    if [ -z "$lpassuser" ]; then
+      exit
+    fi
+    lpass login $lpassuser > /dev/null
+    if [ $? -ne 0 ]; then
+      echo "Failed to login to lastpass" > /dev/stderr
+      exit
+    fi
+  fi
 
   key=${host_map[$host]:-$host}
   user="$(lpass show --username $key)"
   pass="$(lpass show --password $key)"
 
-	if [ "x$user" == "x" ] || [ "x$pass" == "x" ]; then
-		echo "Couldn't find host in lastpass DB." > /dev/stderr
-		exit
-	fi
+  if [ "x$user" == "x" ] || [ "x$pass" == "x" ]; then
+    echo "Couldn't find host in lastpass DB." > /dev/stderr
+    exit
+  fi
 
-	echo username=$user
-	echo password=$pass
+  echo username=$user
+  echo password=$pass
 fi
 
